version: '3.8'

services:
  frontend:
    build:
      context: .
      target: vuebuilder
    container_name: frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
  proxy:
    build:
      context: .
      target: nginx
    container_name: proxy
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  
  backend:
    build:
      context: .
      target: fastapibuilder
    container_name: backend
    ports:
      - "8000:8000"
    command: ["python", "server/src/main.py"]

