version: '3.8'

services:
  frontend:
    build:
      context: .
      target: vuebuilder
    container_name: frontend
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    volumes:
      - ./frontend:/app
    environment:
      - db=nosqldb
    env_file:
      - .env
  
  proxy:
    build:
      context: .
      target: nginx
    container_name: proxy
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    env_file:
      - .env
  
  backend:
    build:
      context: .
      target: fastapibuilder
    container_name: backend
    ports:
      - "8000:8000"
    command: uvicorn server.src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - db=nosqldb
  
  nosqldb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    driver: local

